<?php

namespace Tests\Unit;

use App\Models\CompetitionDay;
use App\Models\Competitor;
use App\Models\CompetitorExportColumn;
use App\Models\PracticeDay;
use App\Models\Sport;
use App\Models\User;
use App\Services\SportDateService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SportDateServiceTest extends TestCase {
	use RefreshDatabase;

	private $sport;
	private $competitionDay;
	private $competitors;
	private $exportColumns;
	private $sportDateService;

	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->sport = factory(Sport::class)->create();
		$this->competitors = factory(User::class, 4)->make()->each(function ($competitor) {
			factory(Competitor::class)->create()->user()->save($competitor);
		});
		$this->competitionDay = factory(CompetitionDay::class)->create([
			'sport_id' => $this->sport->id
		]);
		$this->competitors->each(function ($competitor) {
			$competitor->user->sports()->save($this->sport, ['data' => []]);
			$competitor->user->competitionDays()->attach($this->competitionDay);
		});
		$i = 0;
		$this->exportColumns = factory(CompetitorExportColumn::class, 2)->make()->each(function ($exportColumn) use (&$i) {
			$exportColumn->order = $i;
			if ($i % 2 == 0) {
				$exportColumn->column = 'user.name';
			} else {
				$exportColumn->column = 'user.last_name';
			}
			$exportColumn->save();
			$i = $i + 1;
		});
		$this->sportDateService = new SportDateService($this->competitionDay);
	}

	public function test_sets_headings() {
		$headings = $this->sportDateService->headings();
		$headers = CompetitorExportColumn::orderBy('order')->get()->pluck('name');
		$this->assertEquals($headers->toArray(), $headings);
	}

	public function test_collection() {
		$collection = $this->sportDateService->collection();
		$fields = CompetitorExportColumn::orderBy('order')->get()->pluck('column');
		$data = collect();
		foreach ($this->competitionDay->competitors as $competitor) {
			$data->push($this->listCompetitorData($fields, $competitor));
		}
		$this->assertEquals($data, $collection);

	}

	private function listCompetitorData($fields, Competitor $competitor) {
		$result = collect();
		foreach ($fields as $field) {
			$model = strtok($field, '.');
			$column = strtok('.');
			if ($model === 'user') {
				$result->push($competitor->user->$column);
			} else {
				$result->push($competitor->data[$column] ?? '');
			}
		}
		return $result;
	}
}
